# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('createdAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Starting time for the rule')),
            ],
        ),
    ]
