# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadQuarters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('lat', models.DecimalField(decimal_places=6, help_text='latitude of headquarter', max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, help_text='longitude of headquarter', max_digits=9)),
                ('parking', models.BooleanField(default=False, help_text='has parking?')),
                ('website', models.CharField(blank=True, help_text='headquarter website', max_length=200)),
                ('reservation', models.BooleanField(default=False, help_text='allow reservation?')),
                ('phone', models.CharField(help_text='cellphone, in house phone', max_length=200)),
                ('createdAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Starting time for the rule')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
    ]
