# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('createdAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Starting time for the rule')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.Owner')),
            ],
        ),
    ]
